python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/ooc.jsonnet --dataset-config-path configs/dataset_readers/lexsub/semeval_all.jsonnet --run-dir='debug/lexsub-all-models/semeval_all_ooc' --force --experiment-name='lexsub-all-models' --run-name='semeval_all_ooc'
python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/ooc.jsonnet --dataset-config-path configs/dataset_readers/lexsub/coinco.jsonnet --run-dir='debug/lexsub-all-models/coinco_ooc' --force --experiment-name='lexsub-all-models' --run-name='coinco_ooc'

python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/c2v.jsonnet --dataset-config-path configs/dataset_readers/lexsub/semeval_all.jsonnet --run-dir='debug/lexsub-all-models/semeval_all_c2v' --force --experiment-name='lexsub-all-models' --run-name='semeval_all_c2v'
python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/c2v.jsonnet --dataset-config-path configs/dataset_readers/lexsub/coinco.jsonnet --run-dir='debug/lexsub-all-models/coinco_c2v' --force --experiment-name='lexsub-all-models' --run-name='coinco_c2v'
python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/c2v_embs.jsonnet --dataset-config-path configs/dataset_readers/lexsub/semeval_all.jsonnet --run-dir='debug/lexsub-all-models/semeval_all_c2v_embs' --force --experiment-name='lexsub-all-models' --run-name='semeval_all_c2v_embs'
python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/c2v_embs.jsonnet --dataset-config-path configs/dataset_readers/lexsub/coinco.jsonnet --run-dir='debug/lexsub-all-models/coinco_c2v_embs' --force --experiment-name='lexsub-all-models' --run-name='coinco_c2v_embs'

python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/elmo.jsonnet --dataset-config-path configs/dataset_readers/lexsub/semeval_all.jsonnet --run-dir='debug/lexsub-all-models/semeval_all_elmo' --force --experiment-name='lexsub-all-models' --run-name='semeval_all_elmo'
python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/elmo.jsonnet --dataset-config-path configs/dataset_readers/lexsub/coinco.jsonnet --run-dir='debug/lexsub-all-models/coinco_elmo' --force --experiment-name='lexsub-all-models' --run-name='coinco_elmo'
python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/elmo_embs.jsonnet --dataset-config-path configs/dataset_readers/lexsub/semeval_all.jsonnet --run-dir='debug/lexsub-all-models/semeval_all_elmo_embs' --force --experiment-name='lexsub-all-models' --run-name='semeval_all_elmo_embs'
python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/elmo_embs.jsonnet --dataset-config-path configs/dataset_readers/lexsub/coinco.jsonnet --run-dir='debug/lexsub-all-models/coinco_elmo_embs' --force --experiment-name='lexsub-all-models' --run-name='coinco_elmo_embs'

python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/bert.jsonnet --dataset-config-path configs/dataset_readers/lexsub/semeval_all.jsonnet --run-dir='debug/lexsub-all-models/semeval_all_bert' --force --experiment-name='lexsub-all-models' --run-name='semeval_all_bert'
python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/bert.jsonnet --dataset-config-path configs/dataset_readers/lexsub/coinco.jsonnet --run-dir='debug/lexsub-all-models/coinco_bert' --force --experiment-name='lexsub-all-models' --run-name='coinco_bert'
python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/bert_embs.jsonnet --dataset-config-path configs/dataset_readers/lexsub/semeval_all.jsonnet --run-dir='debug/lexsub-all-models/semeval_all_bert_embs' --force --experiment-name='lexsub-all-models' --run-name='semeval_all_bert_embs'
python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/bert_embs.jsonnet --dataset-config-path configs/dataset_readers/lexsub/coinco.jsonnet --run-dir='debug/lexsub-all-models/coinco_bert_embs' --force --experiment-name='lexsub-all-models' --run-name='coinco_bert_embs'

python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/roberta.jsonnet --dataset-config-path configs/dataset_readers/lexsub/semeval_all.jsonnet --run-dir='debug/lexsub-all-models/semeval_all_roberta' --force --experiment-name='lexsub-all-models' --run-name='semeval_all_roberta'
python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/roberta.jsonnet --dataset-config-path configs/dataset_readers/lexsub/coinco.jsonnet --run-dir='debug/lexsub-all-models/coinco_roberta' --force --experiment-name='lexsub-all-models' --run-name='coinco_roberta'
python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/roberta_embs.jsonnet --dataset-config-path configs/dataset_readers/lexsub/semeval_all.jsonnet --run-dir='debug/lexsub-all-models/semeval_all_roberta_embs' --force --experiment-name='lexsub-all-models' --run-name='semeval_all_roberta_embs'
python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/roberta_embs.jsonnet --dataset-config-path configs/dataset_readers/lexsub/coinco.jsonnet --run-dir='debug/lexsub-all-models/coinco_roberta_embs' --force --experiment-name='lexsub-all-models' --run-name='coinco_roberta_embs'

python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/xlnet.jsonnet --dataset-config-path configs/dataset_readers/lexsub/semeval_all.jsonnet --run-dir='debug/lexsub-all-models/semeval_all_xlnet' --force --experiment-name='lexsub-all-models' --run-name='semeval_all_xlnet'
python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/xlnet.jsonnet --dataset-config-path configs/dataset_readers/lexsub/coinco.jsonnet --run-dir='debug/lexsub-all-models/coinco_xlnet' --force --experiment-name='lexsub-all-models' --run-name='coinco_xlnet'
python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/xlnet_embs.jsonnet --dataset-config-path configs/dataset_readers/lexsub/semeval_all.jsonnet --run-dir='debug/lexsub-all-models/semeval_all_xlnet_embs' --force --experiment-name='lexsub-all-models' --run-name='semeval_all_xlnet_embs'
python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/xlnet_embs.jsonnet --dataset-config-path configs/dataset_readers/lexsub/coinco.jsonnet --run-dir='debug/lexsub-all-models/coinco_xlnet_embs' --force --experiment-name='lexsub-all-models' --run-name='coinco_xlnet_embs'
