python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/elmo.jsonnet --dataset-config-path configs/dataset_readers/lexsub/semeval_all.jsonnet --run-dir='debug/lexsub-all-models/semeval_all_elmo' --force --experiment-name='lexsub-all-models' --run-name='semeval_all_elmo'
python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/elmo.jsonnet --dataset-config-path configs/dataset_readers/lexsub/coinco.jsonnet --run-dir='debug/lexsub-all-models/coinco_elmo' --force --experiment-name='lexsub-all-models' --run-name='coinco_elmo'
python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/elmo_embs.jsonnet --dataset-config-path configs/dataset_readers/lexsub/semeval_all.jsonnet --run-dir='debug/lexsub-all-models/semeval_all_elmo_embs' --force --experiment-name='lexsub-all-models' --run-name='semeval_all_elmo_embs'
python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/elmo_embs.jsonnet --dataset-config-path configs/dataset_readers/lexsub/coinco.jsonnet --run-dir='debug/lexsub-all-models/coinco_elmo_embs' --force --experiment-name='lexsub-all-models' --run-name='coinco_elmo_embs'

python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/bert.jsonnet --dataset-config-path configs/dataset_readers/lexsub/semeval_all.jsonnet --run-dir='debug/lexsub-all-models/semeval_all_bert' --force --experiment-name='lexsub-all-models' --run-name='semeval_all_bert'
python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/bert.jsonnet --dataset-config-path configs/dataset_readers/lexsub/coinco.jsonnet --run-dir='debug/lexsub-all-models/coinco_bert' --force --experiment-name='lexsub-all-models' --run-name='coinco_bert'
python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/bert_embs.jsonnet --dataset-config-path configs/dataset_readers/lexsub/semeval_all.jsonnet --run-dir='debug/lexsub-all-models/semeval_all_bert_embs' --force --experiment-name='lexsub-all-models' --run-name='semeval_all_bert_embs'
python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/bert_embs.jsonnet --dataset-config-path configs/dataset_readers/lexsub/coinco.jsonnet --run-dir='debug/lexsub-all-models/coinco_bert_embs' --force --experiment-name='lexsub-all-models' --run-name='coinco_bert_embs'

python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/xlnet.jsonnet --dataset-config-path configs/dataset_readers/lexsub/semeval_all.jsonnet --run-dir='debug/lexsub-all-models/semeval_all_xlnet' --force --experiment-name='lexsub-all-models' --run-name='semeval_all_xlnet'
python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/xlnet.jsonnet --dataset-config-path configs/dataset_readers/lexsub/coinco.jsonnet --run-dir='debug/lexsub-all-models/coinco_xlnet' --force --experiment-name='lexsub-all-models' --run-name='coinco_xlnet'
python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/xlnet_embs.jsonnet --dataset-config-path configs/dataset_readers/lexsub/semeval_all.jsonnet --run-dir='debug/lexsub-all-models/semeval_all_xlnet_embs' --force --experiment-name='lexsub-all-models' --run-name='semeval_all_xlnet_embs'
python lexsubgen/evaluations/lexsub.py solve --substgen-config-path configs/subst_generators/lexsub/xlnet_embs.jsonnet --dataset-config-path configs/dataset_readers/lexsub/coinco.jsonnet --run-dir='debug/lexsub-all-models/coinco_xlnet_embs' --force --experiment-name='lexsub-all-models' --run-name='coinco_xlnet_embs'
